VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Record"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public id As String
Public count As Integer
Public pageDate As Date
Public item As String
Public pkg As String
Public qty As Integer
Public freight As Currency
Public unloadingFee As Currency
Public transferFee As Currency
Public sum As Currency
Public payment As String
Public comment As String
Public receverName As String
Public receverTel As String
Public receverAdd As String
Public senderName As String
Public senderTel As String
Public senderAdd As String
Public senderId As String
Public driverName As String
Public driverCarNumber As String
Public destination As String
Public collectDate As Date



