VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "PageSummery"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public uploadTime As Date
Public pageDate As Date
Public id As String
Public destination As String
Public driverName As String
Public driverCarNumber As String
Public cost As Currency
Public extraCost As Currency
Public extraCostDesc As String
Public note As String

Public freightAtDestination As Currency
Public freightAtDestinationUnpaid As Currency
Public freightAtBase As Currency
Public freightAtBaseUnpaid As Currency
Public unloadFee As Currency
Public transferFee As Currency
Public totalFreight As Currency
Public totalQty As Integer
Public payAtDestination As Currency


Public profit As Currency






