VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "People"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public name As String
Public tel As String
Public role As String

Public freightAtDestination As Currency
Public freightAtDestinationUnpaid As Currency
Public freightAtBase As Currency
Public freightAtBaseUnpaid As Currency

Public qtyAtDestination As Integer
Public qtyAtDestinationUnpaid As Integer
Public qtyAtBase As Integer
Public qtyAtBaseUnpaid As Integer
