Public pageDate As Date
Public id As String
Public destination As String
Public driverName As String
Public driverCarNumber As String
Public cost As Currency
Public note As String

Public freightAtDestination As Currency
Public freightAtDestinationUnpaid As Currency
Public freightAtBase As Currency
Public freightAtBaseUnpaid As Currency
Public unloadFee As Currency
Public transferFee As Currency
Public totalFreight As Currency
Public totalQty As Integer
Public payAtDestination As Currency


Public profit As Currency



